In [1]:
score = 23

if score >= 80:
    letter = 'A'
elif score >= 60:
    letter = 'B'
elif score >= 50:
    letter = 'C'
elif score >= 45:
    letter = 'D'
elif score>= 25:
    letter = "E"
else:
    letter = 'F'
    
print("The score is: - ", letter)

The score is: -  F


In [19]:
marks = 88
if marks > 25 and marks < 45:
    grade = 'E'
elif marks > 44 and marks <50:
    grade = 'D'
elif marks > 49 and marks <60:
    grade = 'C'
elif marks > 59 and marks <80:
    grade = 'B'
elif marks >= 80:
    grade = 'A'
else:
    grade = 'F'
print('The marks is: ', grade)

The marks is:  A


In [5]:
sentence= "I am going to school"
for i in sentence:
    if i in " AEIOUaeiou.":
        continue
        print(i)

In [1]:
import numpy as np

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [3]:
x=np.array([1,2,3])
print(x)

[1 2 3]


In [11]:
x1=np.array([[1,2,3],[4,5,6]])
print(x1)

[[1 2 3]
 [4 5 6]]


In [18]:
# getting the list of numbers from 1 to 15

for counting_no in range(1, 15, 3):
        print(counting_no)

1
4
7
10
13
